export const resourceTypes = [
	"main_frame",
	"sub_frame",
	"stylesheet",
	"script",
	"image",
	"font",
	"object",
	"xmlhttprequest",
	"ping",
	"csp_report",
	"media",
	"websocket",
	"other",
];
export const requestMethods = ["connect", "delete", "get", "head", "options", "patch", "post", "put"];

export const enumPropKeys = new Set([
	"Resource types",
	"Excluded resource types",
	"Request methods",
	"Excluded request methods",
]);

export const mimeTyeps = [
	"image/vnd.microsoft.icon",
	//audio
	"audio/aac",
	"video/x-msvideo",
	"application/octet-stream",
	"audio/mpeg",
	"audio/ogg",
	//text
	"text/html",
	"text/html",
	"text/html",
	"text/html",
	"text/html",
	"text/plain",
	"text/javascript",
	"text/javascript",
	"text/javascript",
	"text/css",
	"application/json",
	"text/csv",
	"text/markdown",
	//xml
	"application/xhtml+xml",
	"application/xml",
	//document
	"application/msword",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"application/epub+zip",
	"application/pdf",
	"application/x-httpd-php",
	"application/vnd.ms-powerpoint",
	"application/x-sh",
	"application/vnd.ms-excel",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/x-csh",
	//archive
	"application/gzip",
	"application/zip",
	"application/vnd.rar",
	"application/x-7z-compressed",
	"application/x-tar",
	"application/java-archive",
	"application/x-bzip",
	"application/x-bzip2",
	//font
	"font/ttf",
	"font/woff",
	"font/woff2",
	"font/otf",
	"application/vnd.ms-fontobject",
	//image
	"image/bmp",
	"image/png",
	"image/jpg",
	"image/jpeg",
	"image/webp",
	"image/avif",
	"image/svg+xml",
	"mage/heic",
	"image/gif",
	"image/tiff",
	//video
	"video/mp4",
	"video/mpeg",
	"video/ogg",
	"video/3gpp",
	"text/vtt",
];

export const standardRequestHeaders = [
	"A-IM",
	"Accept",
	"Accept-Charset",
	"Accept-Datetime",
	"Accept-Encoding",
	"Accept-Language",
	"Access-Control-Request-Method",
	"Access-Control-Request-Headers",
	"Authorization",
	"Cache-Control",
	"Connection",
	"Content-Encoding",
	"Content-Length",
	"Content-MD5",
	"Content-Type",
	"Cookie",
	"Date",
	"ECT",
	"Expect",
	"Forwarded",
	"From",
	"Host",
	"HTTP2-Settings",
	"If-Match",
	"If-Modified-Since",
	"If-None-Match",
	"If-Range",
	"If-Unmodified-Since",
	"Max-Forwards",
	"Origin",
	"Pragma",
	"Prefer",
	"Proxy-Authorization",
	"Range",
	"Referer",
	"TE",
	"Trailer",
	"Transfer-Encoding",
	"User-Agent",
	"Upgrade",
	"Via",
	"Warning",
];
export const requestHeaders = [
	...standardRequestHeaders,
	"Upgrade-Insecure-Requests",
	"X-Requested-With",
	"DNT",
	"X-Forwarded-For",
	"X-Forwarded-Host",
	"X-Forwarded-Proto",
	"Front-End-Https",
	"X-Http-Method-Override",
	"X-ATT-DeviceId",
	"X-Wap-Profile",
	"Proxy-Connection",
	"X-UIDH",
	"X-Csrf-Token",
	"X-Request-ID",
	"Save-Data",
	"Sec-GPC",
];

export const standardResponseHeaders = [
	"Accept-CH",
	"Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Access-Control-Expose-Headers,Access-Control-Max-Age,Access-Control-Allow-Methods,Access-Control-Allow-Headers",
	"Accept-Patch",
	"Accept-Ranges",
	"Age",
	"Allow",
	"Alt-Svc",
	"Cache-Control",
	"Connection",
	"Content-Disposition",
	"Content-Encoding",
	"Content-Language",
	"Content-Length",
	"Content-Location",
	"Content-MD5",
	"Cross-Origin-Opener-Policy",
	"Cross-Origin-Resource-Policy",
	"Cross-Origin-Embedder-Policy",
	"Content-Range",
	"Content-Type",
	"Date",
	"Delta-Base",
	"Early-Data",
	"ETag",
	"Expires",
	"IM",
	"Last-Modified",
	"Link",
	"Location",
	"P3P",
	"Pragma",
	"Preference-Applied",
	"Proxy-Authenticate",
	"Public-Key-Pins",
	"Retry-After",
	"Server",
	"Set-Cookie",
	"Strict-Transport-Security",
	"Trailer",
	"Transfer-Encoding",
	"Tk",
	"Upgrade",
	"Vary",
	"Via",
	"Warning",
	"WWW-Authenticate",
	"X-Frame-Options",
];
export const responseHeaders = [
	...standardResponseHeaders,
	"Content-Security-Policy",
	"X-Content-Security-Policy",
	"X-WebKit-CSP",
	"Expect-CT",
	"NEL",
	"Permissions-Policy",
	"Refresh",
	"Report-To",
	"Status",
	"Timing-Allow-Origin",
	"X-Content-Duration",
	"X-Content-Type-Options",
	"X-Powered-By",
	"X-Redirect-By",
	"X-Request-ID",
	"X-Correlation-ID",
	"X-UA-Compatible",
	"X-XSS-Protection",
];

export const requestHeaderData = {
	"A-IM": ["feed"],
	Accept: ["text/html"],
	"Accept-Charset": ["utf-8"],
	"Accept-Datetime": [new Date().toUTCString()],
	"Accept-Encoding": ["gzip, deflate"],
	"Accept-Language": ["en-US"],
	"Access-Control-Request-Method": ["CONNECT", "DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"],
	Authorization: ["Basic "],
	"Cache-Control": ["no-cache"],
	Connection: ["Upgrade"],
	"Content-Encoding": ["gzip"],
	"Content-Length": [],
	"Content-MD5": [],
	"Content-Type": ["application/x-www-form-urlencoded"],
	Cookie: [],
	Date: [new Date().toUTCString()],
	ECT: ["slow-2g", "2g", "3g", "4g"],
	Expect: [],
	Forwarded: [],
	From: [],
	Host: [],
	"HTTP2-Settings": ["token64"],
	"If-Match": [],
	"If-Modified-Since": [new Date().toUTCString()],
	"If-None-Match": [],
	"If-Range": [],
	"If-Unmodified-Since": [new Date().toUTCString()],
	"Max-Forwards": [],
	Origin: [],
	Pragma: ["no-cache"],
	Prefer: ["return=representation"],
	"Proxy-Authorization": ["Basic "],
	Range: ["bytes="],
	Referer: [],
	TE: ["trailers, deflate"],
	Trailer: ["Max-Forwards"],
	"Transfer-Encoding": ["chunked"],
	"User-Agent": [
		navigator.userAgent,
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.",
		"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.",
		"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.3",
		"Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.",
	],
	Upgrade: ["h2c, HTTPS/1.3, IRC/6.9, RTA/x11, websocket"],
	Via: ["1.0 fred, 1.1 example.com (Apache/1.1)"],
	Warning: ["199 Miscellaneous warning"],

	"Upgrade-Insecure-Requests": ["1"],
	"X-Requested-With": ["XMLHttpRequest"],
	DNT: ["0"],
	"X-Forwarded-For": [],
	"X-Forwarded-Host": [],
	"X-Forwarded-Proto": ["https"],
	"Front-End-Https": ["on"],
	"X-Http-Method-Override": ["DELETE"],
	"X-ATT-DeviceId": [],
	"X-Wap-Profile": [],
	"Proxy-Connection": ["keep-alive"],
	"X-UIDH": [],
	"X-Csrf-Token": [],
	"X-Request-ID": [],
	"Save-Data": ["on"],
	"Sec-GPC": ["1"],
};

export const responseHeaderData = {
	"Accept-CH": ["UA, Platform"],
	"Access-Control-Allow-Origin": ["*"],
	"Access-Control-Allow-Credentials": [],
	"Access-Control-Expose-Headers": [],
	"Access-Control-Max-Age": [],
	"Access-Control-Allow-Method": ["DELETE", "GET", "HEAD", "PATCH", "POST", "PUT"],
	"Access-Control-Allow-Headers": [],
	"Accept-Patch": ["text/example;charset=utf-8"],
	"Accept-Ranges": ["bytes"],
	Age: [],
	Allow: ["DELETE", "GET", "HEAD", "PATCH", "POST", "PUT"],
	"Alt-Svc": ['8001"; ma=7200'],
	"Cache-Control": [
		"max-age=3600, public",
		"no-cache",
		"no-store",
		"no-transform",
		"must-revalidate",
		"proxy-revalidate",
	],
	Connection: ["close"],
	"Content-Disposition": ['attachment; filename=""'],
	"Content-Encoding": ["gzip", "compress", "deflate", "zstd", "brotli"],
	"Content-Language": ["en-US", "de-DE", "en-CA"],
	"Content-Length": [],
	"Content-Location": [],
	"Content-MD5": [],
	"Content-Range": ["bytes "],
	"Content-Type": mimeTyeps,
	"Cross-Origin-Opener-Policy": ["unsafe-none", "same-origin-allow-popups", "same-origin"],
	"Cross-Origin-Resource-Policy": ["same-site", "same-origin", "cross-origin"],
	"Cross-Origin-Embedder-Policy": ["unsafe-none", "require-corp", "credentialless"],
	Date: [new Date().toUTCString()],
	"Delta-Base": [],
	ETag: [crypto.randomUUID()],
	Expires: [new Date().toUTCString()],
	IM: ["feed"],
	"Last-Modified": [new Date().toUTCString()],
	Link: ['</feed>; rel="alternate"'],
	Location: [""],
	P3P: ['CentralAutoLogin/P3P for more info."'],
	Pragma: ["no-cache"],
	"Preference-Applied": ["return=representation"],
	"Proxy-Authenticate": ["Basic"],
	"Public-Key-Pins": ['max-age=2592000; pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";'],
	"Retry-After": [new Date(Date.now() + 3600).toUTCString()],
	Server: ["Apache/2.4.1 (Unix)"],
	"Set-Cookie": [],
	"Strict-Transport-Security": ["max-age=16070400; includeSubDomains"],
	Trailer: ["Max-Forwards"],
	"Transfer-Encoding": ["chunked", "compress", "deflate", "gzip"],
	Tk: ["?"],
	Upgrade: ["h2c, HTTPS/1.3, IRC/6.9, RTA/x11, websocket"],
	Vary: ["Accept-Language"],
	Via: ["1.0 fred, 1.1 example.com (Apache/1.1)"],
	Warning: ["199 Miscellaneous warning"],
	"WWW-Authenticate": ["Basic"],
	"X-Frame-Options": ["DENY", "SAMEORIGIN"],
	"Content-Security-Policy": ["default-src 'self'"],
	"X-Content-Security-Policy": ["default-src 'self'"],
	"X-WebKit-CSP": ["default-src 'self'"],
	"Expect-CT": [],
	NEL: ["1.0 }"],
	"Permissions-Policy": ["fullscreen=(), camera=(), microphone=(), geolocation=(), interest-cohort=()"],
	Refresh: [""],
	"Report-To": [],
	Status: [
		"200 OK",
		"201 Created",
		"202 Accepted",
		"203 Non-Authoritative Information",
		"204 No Content",
		"205 Reset Content",
		"206 Partial Content",
		"207 Multi-Status",
		"301 Moved Permanently",
		"302 Found",
		"303 See Other",
		"304 Not Modified",
		"307 Temporary Redirect",
		"308 Permanent Redirect",
		"400 Bad Request",
		"401 Unauthorized",
		"403 Forbidden",
		"404 Not Found",
		"405 Method Not Allowed",
		"429 Too Many Requests",
		"500 Internal Server Error",
		"501 Not Implemented",
		"502 Bad Gateway",
	],
	"Timing-Allow-Origin": [],
	"X-Content-Duration": [],
	"X-Content-Type-Options": ["nosniff"],
	"X-Powered-By": ["PHP/5.4.0"],
	"X-Redirect-By": [],
	"X-Request-ID": [crypto.randomUUID()],
	"X-Correlation-ID": [crypto.randomUUID()],
	"X-UA-Compatible": ["Chrome=1"],
	"X-XSS-Protection": ["0", "1; mode=block", "1; report="],
};
